const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, 'blog');
const published = '2026-09-21';
const S = {
  g2019: 'https://blog.google/products-and-platforms/products/maps/google-maps-101-how-contributed-content-makes-maps-helpful/',
  g2020: 'https://blog.google/products-and-platforms/products/maps/google-maps-101-how-we-tackle-fake-and-fraudulent-contributed-content/',
  g2021: 'https://blog.google/products-and-platforms/products/maps/how-we-kept-maps-reliable-2021/',
  g2022: 'https://blog.google/products-and-platforms/products/maps/google-maps-fake-contributions-ai-machine-learning/',
  g2023: 'https://blog.google/products-and-platforms/products/maps/how-machine-learning-keeps-contributed-content-helpful/',
  g2024: 'https://blog.google/products-and-platforms/products/maps/google-business-profiles-ai-fake-reviews/',
  g2025: 'https://blog.google/products-and-platforms/products/maps/new-ways-were-protecting-businesses-on-maps/',
  googleReport: 'https://support.google.com/business/answer/4596773?hl=en',
  googlePolicy: 'https://support.google.com/contributionpolicy/answer/7400114?hl=en',
  trustReport: 'https://corporate.trustpilot.com/trust/trust-report-2025',
  trustCentre: 'https://uk.corporate.trustpilot.com/trust',
  trustGuidelines: 'https://corporate.trustpilot.com/legal/for-businesses/guidelines-for-businesses/may-2025',
  facebook: 'https://www.facebook.com/help/548274415377576/',
  yelpReport: 'https://www.yelp-support.com/article/When-should-I-report-a-review?l=en_US',
  yelpHow: 'https://www.yelp-support.com/article/How-do-I-report-a-review?l=en_US',
  yelpModeration: 'https://www.yelp-support.com/article/000006953?l=en_US',
  tripadvisor: 'https://www.tripadvisor.com/business/en-gb/insights/restaurants/resources/bad-review-response-tips',
  glassdoor: 'https://www.glassdoor.com/blog/responding-to-negative-glassdoor-reviews-faqs/'
};
const a = (href, label) => `<a href="${href}">${label}</a>`;
const cite = (key, label) => a(S[key], label);

const articles = [
  {
    slug: 'google-review-moderation-2019-2025', type: 'Research / Google Maps', art: '292m+', minutes: 7,
    title: 'Google Maps review moderation, 2019–2025: seven years of published figures',
    deck: 'A source-by-source audit of Google’s annual review enforcement figures, with downloadable data, original charts and the limits behind the headline numbers.',
    description: 'Explore Google Maps review moderation data for 2019–2025. Original charts, source links, a downloadable CSV and clear notes on what blocked or removed reviews mean.',
    toc: [['findings','Key findings'],['trend','The seven-year series'],['reported','User-reported reviews'],['interpretation','What the figures mean'],['method','Methods and limitations'],['sources','Sources']],
    body: `
      <p class="lede">Google’s published annual figure for policy-violating Maps reviews rose from <strong>more than 75 million in 2019</strong> to <strong>over 292 million in 2025</strong>. Those figures describe reviews Google blocked or removed, and the earlier 2019 update uses “removed” alone. They are <em>not</em> a count of successful business-owner complaints. ${cite('g2019','Google’s 2019 update')} · ${cite('g2025','Google’s 2025 update')}</p>
      <p>We collected the number stated in each of seven annual Google updates, kept Google’s original qualifier (“over,” “more than,” or a rounded number), and plotted those published values below. The result is a compact reference for anyone writing about review moderation. It also shows why a familiar claim—“292 million reviews were deleted after businesses complained”—would be wrong.</p>
      <div class="stat-strip"><div><strong>292m+</strong><span>Google’s published 2025 figure for policy-violating reviews blocked or removed</span></div><div><strong>7 years</strong><span>2019–2025 annual Google updates included in this audit</span></div><div><strong>1m+</strong><span>Reviews Google said it took down after direct user reports in 2021</span></div></div>
      <h2 id="findings">Key findings</h2>
      <ul><li>The <strong>published threshold</strong> climbed from 75 million-plus for 2019 to 292 million-plus for 2025. Because most values are lower bounds, dividing them does not produce an exact growth rate. ${cite('g2019','2019 source')} · ${cite('g2025','2025 source')}</li><li>Google’s 2020 figure was 55 million, below its 2019 figure. Google said the decline occurred alongside lower review volume during COVID-19. ${cite('g2020','2020 source')}</li><li>Google separately reported reviews taken down after direct user reports for 2019, 2020 and 2021. That narrower measure is different from its total moderation figure. ${cite('g2019','2019 source')} · ${cite('g2020','2020 source')} · ${cite('g2021','2021 source')}</li><li>Google said it published more than 1 billion helpful reviews in 2025, but that figure cannot be used as a clean denominator for the 292 million blocked-or-removed number. Blocked reviews may never have gone live, and both values are rounded lower bounds. ${cite('g2025','2025 source')}</li></ul>
      <h2 id="trend">The seven-year series</h2>
      <p>The chart uses the number in each Google announcement. A “+” means the source said “over” or “more than”; it is not an estimate of the undisclosed exact total. In 2019 Google described reviews <em>removed</em>; later updates use <em>blocked or removed</em>. We preserve that distinction in the table.</p>
      <figure><img src="assets/google-moderation-2019-2025.svg" alt="Google Maps annual reported policy violating review actions: 75 million plus in 2019, 55 million in 2020, 95 million plus in 2021, 115 million plus in 2022, 170 million plus in 2023, 240 million plus in 2024, and 292 million plus in 2025." width="1000" height="560" loading="lazy"><figcaption>Figure 1. Google’s rounded published figures in millions. Most bars show a stated lower bound, not an exact count. <a href="assets/google-moderation-2019-2025.svg" download>Download SVG chart</a>.</figcaption></figure>
      <div class="data-table-wrap"><table><caption class="visually-hidden">Google Maps annual review moderation figures and sources</caption><thead><tr><th>Year</th><th>Published figure</th><th>Google’s measure</th><th>Source</th></tr></thead><tbody>
      <tr><td>2019</td><td>More than 75m</td><td>Removed</td><td>${cite('g2019','Google update')}</td></tr><tr><td>2020</td><td>55m</td><td>Blocked or removed</td><td>${cite('g2020','Google update')}</td></tr><tr><td>2021</td><td>More than 95m</td><td>Blocked or removed</td><td>${cite('g2021','Google update')}</td></tr><tr><td>2022</td><td>Over 115m</td><td>Blocked or removed</td><td>${cite('g2022','Google update')}</td></tr><tr><td>2023</td><td>Over 170m</td><td>Blocked or removed</td><td>${cite('g2023','Google update')}</td></tr><tr><td>2024</td><td>More than 240m</td><td>Blocked or removed</td><td>${cite('g2024','Google update')}</td></tr><tr><td>2025</td><td>Over 292m</td><td>Blocked or removed</td><td>${cite('g2025','Google update')}</td></tr>
      </tbody></table></div>
      <div class="download-row"><a class="download-link" href="data/google-review-moderation-2019-2025.csv" download>Download source table (CSV) ↓</a><a class="download-link" href="assets/google-moderation-2019-2025.svg" download>Download chart (SVG) ↓</a></div>
      <h2 id="reported">What about reviews reported by users?</h2>
      <p>Google also published a narrower count of reviews it took down after people reported them directly: <strong>more than 580,000 in 2019</strong>, <strong>more than 960,000 in 2020</strong> and <strong>more than 1 million in 2021</strong>. These are review takedowns associated with direct reports, not the number of reports filed, and Google did not provide a directly matching figure in every later update in our seven-source set. ${cite('g2019','2019 update')} · ${cite('g2020','2020 update')} · ${cite('g2021','2021 update')}</p>
      <figure><img src="assets/google-user-reported-2019-2021.svg" alt="Google reported taking down more than 580,000 directly reported reviews in 2019, more than 960,000 in 2020, and more than one million in 2021." width="1000" height="420" loading="lazy"><figcaption>Figure 2. A separate subset of review moderation. These numbers do not show the percentage of reports that succeeded. <a href="assets/google-user-reported-2019-2021.svg" download>Download SVG chart</a>.</figcaption></figure>
      <p>For a business owner, the distinction matters. The 2025 total includes content stopped before publication and content removed later by Google’s systems or analysts. It cannot tell you the chance that your own report will result in a takedown. Google’s current ${cite('googleReport','Business Profile reporting guidance')} says reviews must violate its policies to qualify for removal and that evaluation typically takes several days.</p>
      <h2 id="interpretation">What the figures do—and do not—show</h2>
      <p>The series documents what <em>Google said it acted on</em> each year. It does not independently measure how many fake reviews were attempted, how many were visible to users, or how many legitimate reviews were removed by mistake. A higher enforcement number could reflect more attempted abuse, more contributions, better detection, policy changes, or several factors together. Google’s 2024 update, for example, specifically discussed improved algorithms and revisiting older reviews. ${cite('g2024','Google’s 2024 update')}</p>
      <div class="note-box"><h3>Do not turn this into a removal rate</h3><p>The 2025 figures “over 292 million blocked or removed” and “more than 1 billion published” use different populations and both are lower bounds. Dividing 292 by 1,000 would create a percentage Google did not report and these data do not support.</p></div>
      <p>Another limit: “blocked or removed” combines two very different moments. A blocked review may never appear on a listing; a removed review was visible before a later action. Google does not split those two outcomes in the annual headline figures used here. That is why the chart is best cited as a <strong>published moderation series</strong>, not a deletion series.</p>
      <h2 id="method">Methods and limitations</h2>
      <ol><li>We used seven Google-authored public updates describing the calendar years 2019 through 2025. We recorded the review figure and wording in each source; all links are in the table and source list below.</li><li>We converted the stated counts to millions for one chart. “Over” and “more than” remain lower bounds, shown with a plus sign. The 2020 figure and all large totals are rounded by Google.</li><li>We did not scrape reviews, query private dashboards, survey businesses, or verify Google’s internal counts. This is original compilation and analysis of <em>platform-published data</em>, not a new measurement of all reviews.</li><li>We did not calculate year-over-year percentages because the values are rounded lower bounds and the 2019 measure is worded differently. Changes in enforcement methods or definitions could affect comparability.</li></ol>
      <p><strong>Accessed:</strong> September 21, 2026. <strong>Reuse:</strong> You may cite this compilation and download the CSV or SVG with attribution to ReviewRemoval and a link to this article. The original figures remain attributed to Google.</p>
      <div class="note-box"><h3>Suggested citation</h3><p>ReviewRemoval (2026), “Google Maps review moderation, 2019–2025: seven years of published figures,” September 21, 2026. Link to this page and identify Google as the source of the underlying annual counts.</p></div>
      <h2 id="sources">Primary sources</h2>
      <ol class="sources-list"><li>${cite('g2019','Google Maps 101: how contributed content makes a more helpful map')} — 2019 figures.</li><li>${cite('g2020','A look at how we tackle fake and fraudulent contributed content')} — 2020 figures.</li><li>${cite('g2021','How we kept information on Maps reliable in 2021')} — 2021 figures.</li><li>${cite('g2022','New ways we tackle fake contributions on Google Maps')} — 2022 figures.</li><li>${cite('g2023','How machine learning keeps contributed content helpful')} — 2023 figures.</li><li>${cite('g2024','New ways AI helps keep business information trustworthy')} — 2024 figures.</li><li>${cite('g2025','New ways we’re protecting businesses on Maps')} — 2025 figures.</li><li>${cite('googleReport','Google Business Profile Help: report inappropriate reviews')} — current reporting guidance.</li></ol>
    `
  },
  {
    slug: 'trustpilot-fake-reviews-by-star-rating', type: 'Research / Trustpilot', art: '3.4m', minutes: 7,
    title: 'Trustpilot fake reviews by star rating: what its 2024 data actually shows',
    deck: 'Trustpilot’s published breakdown reveals that most detected fake reviews it removed in 2024 were five-star. Here are the figures, calculations and important caveats.',
    description: 'Original analysis of Trustpilot fake reviews removed by star rating in 2024: 3.4 million five-star versus 627,000 one-star, with charts, methods and source data.',
    toc: [['findings','Key findings'],['ratings','By star rating'],['automation','How reviews were found'],['meaning','What the data means'],['method','Methods and limits'],['sources','Sources']],
    body: `
      <p class="lede">Trustpilot said it removed <strong>4.5 million detected fake reviews</strong> in 2024. Its own star-rating breakdown lists <strong>3.4 million five-star</strong> and <strong>627,000 one-star</strong> removals. Using those rounded figures, the five-star count was <strong>about 5.4 times</strong> the one-star count. ${cite('trustReport','Trustpilot Trust Report 2025')}</p>
      <p>This article turns the published breakdown into a clear table and two downloadable charts. The central point is narrow but useful: in Trustpilot’s 2024 detected-and-removed set, fake positive reviews were prominent. The data does not tell us which individual review is fake, how common fake reviews were within <em>all</em> five-star reviews, or what happened to any particular business report.</p>
      <div class="stat-strip"><div><strong>4.5m</strong><span>Detected fake reviews Trustpilot says it removed in 2024</span></div><div><strong>3.4m</strong><span>Of the removed fake reviews, five-star in its rounded breakdown</span></div><div><strong>90%</strong><span>Share of detected fake removals Trustpilot says its technology found automatically</span></div></div>
      <h2 id="findings">Key findings</h2>
      <ul><li>Trustpilot reports that detected fake reviews removed in 2024 equalled <strong>7.4% of reviews submitted that year</strong>. That is a platform-reported detected removal share, not an estimate of all fake reviews that existed. ${cite('trustReport','Trustpilot Trust Report 2025')}</li><li>Its rounded star-rating counts add to <strong>4.483 million</strong>, close to the reported 4.5 million total. The 17,000 difference is consistent with rounding and is not evidence of another category.</li><li>Of the published category sum, five-star reviews account for about <strong>75.8%</strong>. We calculate that as 3.4 million ÷ 4.483 million and label it approximate because Trustpilot rounded the inputs.</li><li>Trustpilot says <strong>90%</strong> of the detected fake reviews removed in 2024 were identified automatically. The remainder came after user flags or manual investigations; this is not a business-report success rate. ${cite('trustReport','Trustpilot Trust Report 2025')}</li></ul>
      <h2 id="ratings">The published star-rating breakdown</h2>
      <p>The chart plots Trustpilot’s published counts, not reconstructed raw records. A bar for three-star reviews looks tiny because the five-star figure is 3.4 million. We keep the same scale for every row so the difference is visible without distortion.</p>
      <figure><img src="assets/trustpilot-fake-reviews-by-star.svg" alt="Trustpilot removed approximately 3.4 million five-star fake reviews, 306,000 four-star, 70,000 three-star, 80,000 two-star and 627,000 one-star fake reviews in 2024." width="1000" height="560" loading="lazy"><figcaption>Figure 1. Detected fake reviews removed in 2024, by rating. Values are rounded in Trustpilot’s report. <a href="assets/trustpilot-fake-reviews-by-star.svg" download>Download SVG chart</a>.</figcaption></figure>
      <div class="data-table-wrap"><table><caption class="visually-hidden">Trustpilot fake reviews removed in 2024 by star rating</caption><thead><tr><th>Rating</th><th>Reported count</th><th>Approx. share of published category sum</th></tr></thead><tbody><tr><td>5 stars</td><td>3.4 million</td><td>75.8%</td></tr><tr><td>4 stars</td><td>306,000</td><td>6.8%</td></tr><tr><td>3 stars</td><td>70,000</td><td>1.6%</td></tr><tr><td>2 stars</td><td>80,000</td><td>1.8%</td></tr><tr><td>1 star</td><td>627,000</td><td>14.0%</td></tr></tbody></table></div>
      <p>The approximate shares use the <strong>sum of the five published rating counts (4.483 million)</strong> as the denominator; they should not be mistaken for exact platform statistics. Trustpilot’s reported headline total is 4.5 million. ${cite('trustReport','Source report')}</p>
      <div class="download-row"><a class="download-link" href="data/trustpilot-fake-reviews-by-star-2024.csv" download>Download source table (CSV) ↓</a><a class="download-link" href="assets/trustpilot-fake-reviews-by-star.svg" download>Download rating chart (SVG) ↓</a></div>
      <h2 id="automation">How Trustpilot says it found them</h2>
      <p>Trustpilot says its automated models detected <strong>90%</strong> of the 4.5 million fake reviews removed in 2024. The other detected fake reviews were identified after users flagged content or its teams investigated manually. Its report also says it screens every submitted review before publication, though detection can continue afterward. ${cite('trustReport','Trustpilot Trust Report 2025')}</p>
      <figure><img src="assets/trustpilot-detection.svg" alt="Trustpilot says 90 percent of detected fake reviews removed in 2024 were identified automatically and the remaining 10 percent after flags or manual investigations." width="1000" height="290" loading="lazy"><figcaption>Figure 2. Detection route as described by Trustpilot. The 10% is the complement of the rounded 90% statement, not a separate count of owner reports. <a href="assets/trustpilot-detection.svg" download>Download SVG chart</a>.</figcaption></figure>
      <p>A newer ${cite('trustCentre','Trustpilot Trust Centre')} currently lists <strong>7.8 million</strong> reviews detected as fake and removed in 2025. It does not publish a star-rating split on that page, so the rating analysis above remains tied to 2024. We will not project the 2024 proportions onto 2025 without the missing data.</p>
      <h2 id="meaning">What this means for a business</h2>
      <p>The results challenge the idea that fake-review enforcement is only about one-star attacks: many detected fake reviews removed by Trustpilot were highly positive. But the chart cannot reveal the probability that a randomly chosen five-star or one-star review is fake. For that, we would need the number of <em>all submitted reviews at each star rating</em>, which is not supplied in this breakdown.</p>
      <p>Trustpilot’s ${cite('trustGuidelines','business guidelines')} say a business can flag a review that breaches its rules, while disliking a rating or disagreeing with criticism is not a valid reason. The platform also says it may act against misuse of its flagging tools. A useful report should therefore identify the specific content concern and provide evidence where available.</p>
      <div class="note-box"><h3>Avoid a common false conclusion</h3><p>“75.8% of five-star reviews are fake” is <strong>not</strong> supported. About 75.8% of the <em>rounded, detected fake removals in this rating breakdown</em> were five-star. Those are entirely different denominators.</p></div>
      <h2 id="method">Methods and limits</h2>
      <ol><li>We transcribed Trustpilot’s five rating counts, reported 4.5 million total, 7.4% detected-removal share and 90% automated-detection share from its Trust Report 2025, which covers 2024 activity.</li><li>We summed the five rounded counts: 3,400,000 + 306,000 + 70,000 + 80,000 + 627,000 = 4,483,000. We divided each category by that sum for approximate shares; percentages may not sum to exactly 100% after rounding.</li><li>We calculated the five-star to one-star ratio as 3,400,000 ÷ 627,000 ≈ 5.4. It is an approximate ratio of <em>removed detected fake review counts</em>, not a comparison of fraud rates.</li><li>The source is platform self-reporting. We did not independently inspect review-level data. “Detected fake” excludes fake reviews not detected. We do not infer causes, intent, or rates for businesses or countries.</li></ol>
      <p><strong>Accessed:</strong> September 21, 2026. <strong>Reuse:</strong> You may cite this analysis and download its CSV or SVG with attribution to ReviewRemoval and a link to this article. Attribute the original counts to Trustpilot.</p>
      <div class="note-box"><h3>Suggested citation</h3><p>ReviewRemoval (2026), “Trustpilot fake reviews by star rating: what its 2024 data actually shows,” September 21, 2026. Link to this page and identify Trustpilot as the source of the underlying counts.</p></div>
      <h2 id="sources">Primary sources</h2><ol class="sources-list"><li>${cite('trustReport','Trustpilot Trust Report 2025')} — 2024 figures, star breakdown, 7.4% and automation share.</li><li>${cite('trustCentre','Trustpilot Trust Centre')} — current 2025 detected fake removal headline.</li><li>${cite('trustGuidelines','Trustpilot guidelines for businesses')} — review flagging and misuse rules.</li></ol>
    `
  },
  {
    slug: 'review-removal-questions-answered', type: 'Guide / Frequently asked questions', art: '14', minutes: 7,
    title: 'Common review removal questions, answered',
    deck: 'Fourteen direct answers about Google, Facebook, Yelp, Trustpilot, Tripadvisor and Glassdoor reporting, timelines, appeals and pricing.',
    description: 'Answers to common review removal questions: which reviews qualify, how reporting and appeals work, platform differences, timelines and service costs.',
    toc: [['basics','Eligibility and control'],['google','Google reviews'],['other','Other platforms'],['service','Working with us'],['sources','Sources']],
    body: `
      <p class="lede">A bad review and a removable review are not the same thing. Platforms generally assess reports against their own rules. These answers explain the difference and link to the source behind each platform-specific point.</p>
      <h2 id="basics">Eligibility and control</h2>
      <h3>1. Can a business delete a customer review itself?</h3><p>Usually the business can report or flag the review, but the platform evaluates it. Google says policy-violating reviews can be reported for removal; Trustpilot says reviewers own their own reviews and can edit or delete them. A service like ours can assess, prepare and manage the process, but cannot force a platform decision. ${cite('googleReport','Google Business Profile Help')} · ${cite('trustGuidelines','Trustpilot business guidelines')}</p>
      <h3>2. Is a negative review enough to request removal?</h3><p>No. Google says not to report a review merely because you dislike or disagree with it. Trustpilot says the same about a low rating or criticism. Look for a specific rule the content may violate, then provide relevant facts. ${cite('googleReport','Google reporting guidance')} · ${cite('trustGuidelines','Trustpilot guidelines')}</p>
      <h3>3. What if the reviewer was never a customer?</h3><p>Google’s policy requires reviews to reflect genuine experiences. Yelp’s guidance focuses on the reviewer’s own consumer experience. However, a business’s inability to find a matching name in its records is not, on its own, proof that no interaction happened. Document what you can establish and avoid claiming certainty without evidence. ${cite('googlePolicy','Google Maps content policy')} · ${cite('yelpReport','Yelp reporting guidance')}</p>
      <h3>4. What if the reviewer is a competitor or former employee?</h3><p>Google’s rating-manipulation policy includes conflicts of interest such as current or former employment and industry competitors. Yelp lists apparent conflicts of interest among its main reporting reasons and asks for specific evidence. The relationship and evidence matter more than an unsupported suspicion. ${cite('googlePolicy','Google Maps policy')} · ${cite('yelpReport','Yelp guidance')}</p>
      <h2 id="google">Google Business Profile reviews</h2>
      <h3>5. Which Google reviews are eligible for removal?</h3><p>Google says only reviews that violate its policies qualify. Its policy covers fake engagement, rating manipulation, off-topic content and other prohibited material. Critical feedback about a genuine experience may remain, even when a business disputes the account. ${cite('googleReport','Google reporting guidance')} · ${cite('googlePolicy','Google Maps content policy')}</p>
      <h3>6. How do I report a Google review?</h3><p>From your Business Profile, open <em>Read reviews</em>, choose the review, select <em>Report</em>, choose a reason and submit. Google also offers a Reviews Management Tool to file and track reports. Interface labels may change, so use Google’s current help page for exact steps. ${cite('googleReport','Google’s step-by-step guide')}</p>
      <h3>7. How long does Google take to decide?</h3><p>Google says review evaluation typically takes several days. That is guidance, not a deadline. The Reviews Management Tool can show whether a decision is pending, no violation was found, or an appeal was escalated. ${cite('googleReport','Google reporting guidance')}</p>
      <h3>8. Can I appeal if Google leaves the review up?</h3><p>Google describes a one-time appeal for eligible reviews after a no-violation decision. Its current tool instructions allow selecting up to ten reviews for an appeal. Check the tool for your own profile and review status. ${cite('googleReport','Google appeal steps')}</p>
      <h2 id="other">Facebook, Yelp, Trustpilot, Tripadvisor and Glassdoor</h2>
      <h3>9. Can I remove one Facebook recommendation by switching Recommendations off?</h3><p>No. Meta says turning Recommendations off disables that feature and removes the Page’s rating and reviews from display as a whole. Meta also says you can report an individual Recommendation or review if it does not follow Community Standards. ${cite('facebook','Meta Help Center')}</p>
      <h3>10. Does Yelp’s “not recommended” label mean the review was removed?</h3><p>No. Yelp’s recommendation software and its content-moderation reports are separate. A review can be not currently recommended without being removed. Yelp says reporting a review does not guarantee removal. ${cite('yelpModeration','Yelp moderation guidance')} · ${cite('yelpReport','Yelp reporting guidance')}</p>
      <h3>11. Can a business flag a Trustpilot review for being unfair?</h3><p>Trustpilot says businesses may flag reviews that breach its guidelines, but a disliked star rating or disagreement with a negative account is not a valid reason. Its content integrity process makes the decision. ${cite('trustGuidelines','Trustpilot guidelines')}</p>
      <h3>12. Can Tripadvisor remove a review posted to the wrong property?</h3><p>Tripadvisor lists a review on the wrong property as one circumstance for submitting a concern. It directs registered owners to the Reviews area of the Management Center. Tripadvisor says no removal is guaranteed. ${cite('tripadvisor','Tripadvisor for Business')}</p>
      <h3>13. Can an employer flag a Glassdoor review?</h3><p>Glassdoor says employers can use the flag icon beneath a review to request another moderation look. It assesses the content against its guidelines; disagreement alone need not warrant removal. ${cite('glassdoor','Glassdoor guidance')}</p>
      <h2 id="service">Working with ReviewRemoval</h2>
      <h3>14. What does your service cost, and when is the success fee due?</h3><p>Our published rate is <strong>CAD $50 upfront per review</strong> and <strong>CAD $125 for each review successfully removed</strong>, across the platforms listed on this site. An enquiry is free. We confirm any applicable taxes and written service terms before payment. If several reviews are submitted, the fees apply separately to each review.</p>
      <div class="note-box"><h3>What to send with a request</h3><p>Share the exact review or profile link, the platform name, the number of reviews and a short explanation of the concern. Keep relevant records available, but do not send account passwords or sensitive customer data through a public form. See our <a href="review-report-evidence-checklist.html">evidence checklist</a> for a practical way to organize the facts.</p></div>
      <h2 id="sources">Official guidance used</h2><ol class="sources-list"><li>${cite('googleReport','Google Business Profile: report inappropriate reviews')}</li><li>${cite('googlePolicy','Google Maps prohibited and restricted content policy')}</li><li>${cite('facebook','Meta Help: Page Recommendations')}</li><li>${cite('yelpReport','Yelp Support: when to report a review')}, ${cite('yelpHow','how to report')}, and ${cite('yelpModeration','how moderation differs from recommendations')}</li><li>${cite('trustGuidelines','Trustpilot guidelines for businesses')}</li><li>${cite('tripadvisor','Tripadvisor for Business: submitting a concern')}</li><li>${cite('glassdoor','Glassdoor: negative review FAQs')}</li></ol>
    `
  },
  {
    slug: 'review-report-evidence-checklist', type: 'Guide / Reporting', art: '01–05', minutes: 6,
    title: 'What evidence helps when you report a review?',
    deck: 'A five-step checklist for turning a vague concern into a focused, policy-based report without overstating what you know.',
    description: 'A practical evidence checklist for reporting a potentially policy-violating review on Google, Yelp, Trustpilot and other review platforms.',
    toc: [['principle','Start with the policy'],['checklist','Five-step checklist'],['examples','Evidence examples'],['avoid','What to avoid'],['sources','Sources']],
    body: `
      <p class="lede">A report is easier to assess when it identifies the exact review, the relevant rule and the facts supporting the concern. “This is fake” or “this is unfair” is rarely enough on its own. Google and Yelp both ask reporters to focus on policy violations rather than simple disagreement. ${cite('googleReport','Google reporting guidance')} · ${cite('yelpReport','Yelp reporting guidance')}</p>
      <h2 id="principle">Start with the platform’s rule</h2>
      <p>Read the platform guidance before gathering a large file of screenshots. Google’s policy covers genuine experience, conflicts of interest, incentives, off-topic posts and other prohibited content. Yelp points to conflicts of interest, reviews that are not about the author’s own consumer experience, and inappropriate material. Trustpilot says a business should flag a review for a guideline reason, not simply because it is critical. ${cite('googlePolicy','Google Maps policy')} · ${cite('yelpReport','Yelp guidance')} · ${cite('trustGuidelines','Trustpilot guidelines')}</p>
      <p>Once you have a plausible rule, collect only the information that helps evaluate <em>that</em> rule. More attachments do not automatically make a stronger case.</p>
      <h2 id="checklist">The five-step evidence checklist</h2>
      <ol><li><strong>Save the exact location.</strong> Keep the direct review URL if available, plus the business profile or listing URL. A screenshot helps preserve the wording and date if the review is edited later.</li><li><strong>Record a short timeline.</strong> Note when the review appeared, any related contact and any relevant change to the post. Use dates you can substantiate.</li><li><strong>Identify one primary policy concern.</strong> Choose the most specific rule supported by the material, such as a clear conflict of interest or review of the wrong property. Multiple speculative accusations can obscure the strongest point.</li><li><strong>Attach proportionate evidence.</strong> Useful examples can include a public affiliation, a copy of a message connected to a threat, or booking details with private data removed. Do not upload a customer’s personal information unless the platform specifically requests it through a secure channel.</li><li><strong>Write a concise explanation.</strong> State what the review says, what the rule says and how the evidence connects the two. Keep opinion and confirmed fact separate.</li></ol>
      <div class="note-box"><h3>A clear report in three sentences</h3><p><em>“This review appears on our [platform] listing at [link]. We believe it may conflict with [specific policy] because [verifiable fact]. The attached material shows [relevant connection], and we ask the platform to review it under that rule.”</em> This is an illustration, not a guarantee that any platform will agree.</p></div>
      <h2 id="examples">Match evidence to the concern</h2>
      <div class="data-table-wrap"><table><caption class="visually-hidden">Evidence examples by review concern</caption><thead><tr><th>Possible concern</th><th>Useful detail</th><th>Important limit</th></tr></thead><tbody><tr><td>Conflict of interest</td><td>Documented employment, competitor or close affiliation</td><td>A shared surname or suspicion alone may be weak</td></tr><tr><td>Wrong business or property</td><td>Distinct name, address or booking reference with private details removed</td><td>A factual dispute about a real visit is different</td></tr><tr><td>Threat or extortion</td><td>Related messages, dates and account identifiers</td><td>Keep original records; avoid public accusations</td></tr><tr><td>Private information in a review</td><td>The precise passage and why it identifies someone</td><td>Do not repeat personal data in public responses</td></tr></tbody></table></div>
      <p>These examples are editorial guidance, not a list of automatic removal grounds. The platform decides which facts are relevant. Google’s ${cite('googlePolicy','Maps policy')} and Yelp’s ${cite('yelpReport','reporting guidance')} illustrate why the nature of the content matters. Tripadvisor also lists a review posted to the wrong property among reportable concerns. ${cite('tripadvisor','Tripadvisor for Business')}</p>
      <h2 id="avoid">What to avoid while a report is pending</h2>
      <ul><li><strong>Do not pay for a review change.</strong> Google prohibits incentives for a review, revision or removal of a negative review. ${cite('googlePolicy','Google Maps policy')}</li><li><strong>Do not make claims you cannot verify.</strong> A platform may leave a review live when the issue is only a factual dispute or dissatisfaction. ${cite('googleReport','Google reporting guidance')} · ${cite('yelpReport','Yelp guidance')}</li><li><strong>Do not treat a public reply as a complaint form.</strong> If you respond, write for future readers and avoid publishing private information or accusations. Tripadvisor’s management-response policy specifically restricts personal information and review-fraud accusations. ${a('https://www.tripadvisor.com/Trust-lpgT1CmsfQ3E.html','Tripadvisor response guidelines')}</li><li><strong>Keep the original record.</strong> If the platform asks for more context or offers an appeal, you will have a consistent account of what you submitted.</li></ul>
      <p>Google says review evaluation typically takes several days and its Reviews Management Tool can show report status and eligible one-time appeal options. Other platforms use their own workflows. A careful initial report saves time, but no checklist can make a review eligible if it does not violate the applicable policy. ${cite('googleReport','Google Business Profile Help')}</p>
      <h2 id="sources">Primary sources</h2><ol class="sources-list"><li>${cite('googlePolicy','Google Maps prohibited and restricted content policy')}</li><li>${cite('googleReport','Google Business Profile review reporting and appeal guide')}</li><li>${cite('yelpReport','Yelp Support: when should I report a review?')}</li><li>${cite('trustGuidelines','Trustpilot guidelines for businesses')}</li><li>${cite('tripadvisor','Tripadvisor for Business: reviews and reports')}</li><li>${a('https://www.tripadvisor.com/Trust-lpgT1CmsfQ3E.html','Tripadvisor management response guidelines')}</li></ol>
    `
  }
];

const escapeHtml = value => String(value).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
function head(title, description) { return `<!doctype html>\n<html lang="en-CA">\n<head>\n  <meta charset="utf-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1">\n  <meta name="theme-color" content="#17353e">\n  <meta name="description" content="${escapeHtml(description)}">\n  <meta name="author" content="ReviewRemoval">\n  <title>${escapeHtml(title)} | ReviewRemoval</title>\n  <link rel="icon" href="../favicon.svg" type="image/svg+xml">\n  <link rel="stylesheet" href="../styles.css">\n  <link rel="stylesheet" href="blog.css">\n  <script src="../script.js" defer></script>\n</head>`; }
function header() { return `<a class="skip-link" href="#main">Skip to content</a><div class="topline"><div class="wrap topline-inner"><span>Thoughtful guidance for business owners</span><span>Serving Toronto, Ontario and all of Canada</span></div></div><header class="site-header"><div class="wrap header-inner"><a class="brand" href="../index.html" aria-label="ReviewRemoval home"><span class="brand-mark" aria-hidden="true">R</span><span class="brand-name">Review<span>Removal</span><small>REPUTATION SERVICES</small></span></a><nav class="primary-nav" id="primary-nav" aria-label="Main navigation"><a href="../index.html">Home</a><a href="../platforms.html">Platforms</a><a href="../index.html#pricing">Pricing</a><a href="index.html" aria-current="page">Blog</a><a href="../about.html">About</a><a class="nav-contact" href="../index.html#quote">Get my quote <span aria-hidden="true">↗</span></a></nav><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="primary-nav" aria-label="Open menu"><span></span><span></span><span></span></button></div></header>`; }
function footer() { return `<footer class="site-footer"><div class="wrap footer-main"><div><a class="footer-brand" href="../index.html">Review<span>Removal</span></a><p>Managed review reporting services and clear guidance for Canadian businesses.</p></div><div class="footer-nav"><a href="../index.html">Home</a><a href="../platforms.html">Platforms</a><a href="index.html">Blog</a><a href="../about.html">About</a><a href="../index.html#quote">Get a quote</a></div><div class="footer-note"><strong>Put it in our hands.</strong><p>ReviewRemoval is an independent service. Each platform makes its own moderation decisions under its policies.</p></div></div><div class="wrap footer-bottom"><span>© 2026 ReviewRemoval</span><span>Research and sources checked September 21, 2026</span><a href="#top">Back to top ↑</a></div></footer>`; }
function related(current) { return articles.filter(article => article.slug !== current).slice(0,3).map(article => `<a href="${article.slug}.html"><small>${article.type}</small><strong>${article.title}</strong><span>Read article ↗</span></a>`).join(''); }
function articlePage(article) { return `${head(article.title, article.description)}\n<body class="blog-page"><div id="top"></div>${header()}<main id="main"><header class="article-hero"><div class="wrap"><nav class="article-breadcrumb" aria-label="Breadcrumb"><a href="../index.html">Home</a><span>/</span><a href="index.html">Blog</a><span>/</span><span>Article</span></nav><span class="content-kicker">${article.type}</span><h1>${article.title}</h1><p class="article-deck">${article.deck}</p><div class="article-meta"><span>By <a href="../about.html">ReviewRemoval</a></span><time datetime="${published}">September 21, 2026</time><span>${article.minutes} min read</span><span>Sources checked September 2026</span></div></div></header><div class="wrap article-layout"><article class="article-body">${article.body}<section class="article-cta"><h2>Need help with a specific review?</h2><p>Send the platform and the review link. We’ll assess the details and explain the price before paid work begins.</p><a class="button button-accent" href="../platforms.html">Find your platform <span aria-hidden="true">→</span></a></section></article><aside class="article-sidebar" aria-label="Article navigation"><strong>On this page</strong><nav>${article.toc.map(([id,label]) => `<a href="#${id}">${label}</a>`).join('')}</nav><div class="sidebar-quote"><span>Need help?</span><p>One team to assess, prepare and handle your review concern.</p><a href="../platforms.html">Choose your platform ↗</a></div></aside></div><section class="article-related"><div class="wrap"><p class="eyebrow"><span></span> Keep reading</p><h2>Related articles</h2><div class="article-related-grid">${related(article.slug)}</div></div></section></main>${footer()}</body></html>\n`; }

for (const article of articles) fs.writeFileSync(path.join(root, `${article.slug}.html`), articlePage(article), 'utf8');

const featured = articles[0];
const archive = articles.slice(1).map((article, i) => `<a class="article-card" href="${article.slug}.html"><div class="card-top"><span class="content-kicker">${article.type}</span><span class="card-art" aria-hidden="true">${['★','?','↗'][i]}</span></div><h3>${article.title}</h3><p>${article.deck}</p><div class="card-bottom"><span>${article.minutes} min read</span><span aria-hidden="true">↗</span></div></a>`).join('');
const index = `${head('Review Removal Research & Guides', 'Original analysis of published review moderation data, practical reporting guides and answers to common review removal questions for Canadian businesses.')}\n<body class="blog-index"><div id="top"></div>${header()}<main id="main"><section class="blog-hero"><div class="wrap"><p class="eyebrow"><span></span> The ReviewRemoval journal</p><h1>Better decisions start with <em>better information.</em></h1><p class="blog-hero-lead">Source-led research on review moderation and practical guides for business owners. Read the methods, check the citations and use the charts.</p><div class="blog-rail"><span>Original data analysis</span><span>Platform guidance</span><span>Clear methods and limits</span></div></div></section><section class="blog-featured"><div class="wrap"><div class="blog-section-head"><div><p class="eyebrow"><span></span> Featured research</p><h2>Start with the data.</h2></div><p>Our figures are drawn from linked platform publications, with calculations and limits shown beside the charts.</p></div><div class="featured-grid"><div class="featured-art"><span>GOOGLE MAPS / 2019–2025</span><strong>292m+</strong><small>Google’s published 2025 count of policy-violating reviews blocked or removed</small></div><div class="featured-copy"><span class="content-kicker">${featured.type}</span><h3>${featured.title}</h3><p>${featured.deck}</p><div class="content-meta"><time datetime="${published}">Sep 21, 2026</time><span>${featured.minutes} min read</span></div><a class="text-link" href="${featured.slug}.html">Read the study <span aria-hidden="true">→</span></a></div></div></div></section><section class="blog-archive"><div class="wrap"><div class="blog-section-head"><div><p class="eyebrow"><span></span> More to read</p><h2>Research and field guides.</h2></div></div><div class="article-cards">${archive}</div></div></section><section class="blog-subscribe"><div class="wrap"><div><p class="eyebrow"><span></span> Your review concern</p><h2>When you’re ready, let us handle the work.</h2></div><a class="button button-dark" href="../platforms.html">Find your platform <span aria-hidden="true">→</span></a></div></section></main>${footer()}</body></html>\n`;
fs.writeFileSync(path.join(root, 'index.html'), index, 'utf8');
console.log('Built blog index and', articles.length, 'articles');
