const D = require('./research-data.cjs');
const link = (key,label) => `<a href="${D.sources[key]}">${label}</a>`;
const n = value => value.toLocaleString('en-CA');
const pct = (part,total) => (part/total*100).toFixed(2);
const table = (caption,headers,rows) => `<p class="research-small table-caption">${caption}</p><div class="data-table-wrap" tabindex="0" role="region" aria-label="${caption}"><table><caption class="visually-hidden">${caption}</caption><thead><tr>${headers.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map((v,i)=>i===0?`<th scope="row">${v}</th>`:`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="table-scroll-hint">Scroll the table sideways to see every column.</p>`;
const Y = D.yelp;
module.exports = [
  {
    slug:'yelp-reviews-disappear-reappear-data',type:'Research / Yelp',art:'66,922',minutes:8,
    published:'2026-09-27',dateLabel:'September 27, 2026',
    title:'Why Yelp reviews disappear and reappear: a data audit',
    description:'Yelp reviews missing or returning? Explore a 66,922-review transition table, original calculations, downloadable CSVs and a practical tracking method.',
    deck:'A hidden review can return. We reconstruct a published recommendation matrix, separate movement from deletion, and show how to investigate changes without guessing.',
    serviceHref:'../remove-yelp-reviews.html#quote',serviceLabel:'Get help with a Yelp review',
    toc:[['answer','The short answer'],['matrix','The transition matrix'],['calculations','Our calculations'],['cohorts','Four observation windows'],['rating','A rating without new reviews'],['track','A practical tracking sheet'],['questions','Questions business owners ask'],['method','Methods and limits'],['sources','Primary sources']],
    body:`
      <p class="lede">A Yelp review can leave the main review list without being deleted. It may move into the not recommended section and later return. A useful investigation starts by recording <strong>which state changed</strong>, rather than treating every missing review as a successful removal.</p>
      <h2 id="answer">Why did my Yelp review disappear, then come back?</h2>
      <p>${link('yelpHelp','Yelp’s current explanation')} separates automated recommendations from content moderation. Reviews outside the recommended set remain accessible through a secondary link but do not contribute to the displayed review count or overall rating. Yelp says recommendations can change as more information becomes available; advertising does not influence the software and staff cannot override an individual recommendation.</p>
      <p>There is also a published longitudinal study. Ryan Amos, Roland Maio, Prateek Mittal and Joseph A. Calandrino’s <em>Reviews in Motion</em> follows review classifications over repeated observations. Its Table II contains <strong>${n(Y.total)} reviews visible in both 2012 and 2020 snapshots</strong>. We use those four cells for the calculations below. ${link('yelpPaper','Research paper, Table II, page 3')}</p>
      <div class="stat-strip"><div><strong>${n(Y.total)}</strong><span>Matched reviews in the historical two-snapshot matrix</span></div><div><strong>${n(Y.switched)}</strong><span>Reviews whose observed classification differed</span></div><div><strong>+${n(Y.net)}</strong><span>Net change in recommended reviews within that matched sample</span></div></div>
      <h2 id="matrix">The four-cell matrix most summaries leave out</h2>
      <p>A before-and-after total hides two directions of movement. A recommended count could stay almost unchanged while many individual reviews swap places. The matrix preserves that information.</p>
      ${table('Historical matched reviews: original state versus later state',['2012 state','Recommended in 2020','Not recommended in 2020','Row total'],[
        ['Recommended',n(56048),n(2249),n(Y.starting('Recommended'))],
        ['Not recommended',n(3566),n(5059),n(Y.starting('Not Recommended'))]
      ])}
      <p class="research-small">Source counts: ${link('yelpPaper','Amos et al., Table II')}. Row totals and the calculations below are ours. This is a historical matched sample, not a 2026 Canadian estimate.</p>
      <figure><img src="assets/yelp-review-transitions.svg" width="1200" height="672" loading="lazy" alt="Of 58,297 initially recommended matched reviews, 2,249 changed to not recommended; of 8,625 initially not recommended reviews, 3,566 changed to recommended."><figcaption>Figure 1. Each row uses its own original-state denominator. The different row sizes matter. ${link('yelpPaper','Source: Table II')}. <a href="assets/yelp-review-transitions.svg" download>Download the original SVG chart</a>.</figcaption></figure>
      <h2 id="calculations">Three calculations that answer different questions</h2>
      <h3>1. How much movement occurred overall?</h3>
      <p>The changed-state count is 2,249 + 3,566 = <strong>${n(Y.switched)}</strong>. Divide by ${n(Y.total)} matched reviews: <strong>${pct(Y.switched,Y.total)}%</strong>. This describes the share with different endpoint states. With only two observations, a review that changed twice and returned to its original state would look unchanged.</p>
      <h3>2. Which starting group changed more often?</h3>
      <p>For initially recommended reviews, 2,249 ÷ 58,297 = <strong>${pct(Y.outgoing,Y.starting('Recommended'))}%</strong>. For initially not recommended reviews, 3,566 ÷ 8,625 = <strong>${pct(Y.incoming,Y.starting('Not Recommended'))}%</strong>. The denominators are different, so comparing the raw counts alone misses the size of each starting group.</p>
      <p>These conditional proportions are retrospective descriptions of this sample. They are not the probability that your missing review will return, a reason to wait eight years, or evidence of a method for influencing the software.</p>
      <h3>3. How much change would a simple count miss?</h3>
      <p>The net recommended gain is 3,566 − 2,249 = <strong>${n(Y.net)}</strong>. Gross observed movement is ${n(Y.switched)}. That is <strong>${(Y.switched/Y.net).toFixed(2)} times</strong> the net change. A dashboard that tracks only the net total loses the identity and direction of thousands of changes in this example.</p>
      <div class="download-row"><a class="download-link" href="data/yelp-reclassification-2012-2020.csv" download>Download the transition data (CSV)</a><a class="download-link" href="data/yelp-longitudinal-cohorts.csv" download>Download cohort details (CSV)</a></div>
      <h2 id="cohorts">Four observation windows, four different contexts</h2>
      ${table('Published study cohorts: do not interpret these as annual rates',['Cohort','Window','Businesses','Unique reviews','Crawls','Reclassified'],D.cohorts.map(r=>[r.name,r.period,n(r.businesses),n(r.unique),r.crawls,`${r.reclassified}%`]))}
      <p class="research-small">${link('yelpPaper','Table I, page 3')}: EYG is the eight-year comparison; CHI covers Chicago; UDS and UIS stratify US areas by density and income. The research concerns US samples, not Canadian cities.</p>
      <p>Do not rank these percentages as if the samples ran for the same length of time. Two snapshots cannot observe every intermediate transition. Four or eight crawls offer more chances to see movement, but the sampling intervals and review populations also differ. Dividing a cumulative share by months would impose an unsupported constant-rate model.</p>
      <h2 id="rating">Can my rating change without any new reviews?</h2>
      <p>Yes, a change in the reviews included in an average can change the average. Consider an <strong>illustrative arithmetic example</strong>: eight five-star ratings and two one-star ratings total 42 stars across ten reviews, or 4.2. If one of the one-star ratings stops being included, the mean becomes 41 ÷ 9 = 4.556. If a five-star rating instead stops being included, it becomes 37 ÷ 9 = 4.111.</p>
      <p>This example uses a simple mean to isolate the effect of changing membership. It is not an observed business, a prediction of Yelp’s exact display rounding, or a claim that recommendations favour one star level. It explains why tracking only new submissions is insufficient when you investigate a changed score.</p>
      <h2 id="track">A tracking sheet for Canadian businesses</h2>
      <p>For a Toronto restaurant, Vancouver service business or another Canadian listing, record changes on the exact profile. Start with a baseline and check again at a consistent interval. Weekly checks can be a manageable workflow; that is our operational suggestion, not a platform deadline or a statistically validated observation schedule.</p>
      <ol><li><strong>Record the review URL and time.</strong> Use the same local time zone, or UTC, for every observation. Preserve the original post rather than relying on a changing total.</li><li><strong>Record the state separately.</strong> Use recommended, not recommended, unavailable, or unknown. “Unavailable” should not automatically be labelled “removed for a policy violation.”</li><li><strong>Record the visible rating and count.</strong> Keep these as observations. Do not assume a rounded score reveals the complete underlying distribution.</li><li><strong>Record any actual moderation message.</strong> Store the case reference and wording separately from your interpretation of the page.</li><li><strong>Follow the individual review.</strong> If it returns, change its state in your log. Avoid counting the same review as several distinct removals.</li></ol>
      <p>Use our <a href="data/review-status-tracking-template.csv" download>blank tracking template</a>. It contains headings, not customer data. Keep private account messages out of anything you publish.</p>
      <h2 id="questions">Questions business owners ask</h2>
      <h3>Does “not recommended” prove that a review is fake?</h3><p>No. It is a recommendation state, not a verified finding about the reviewer’s honesty. ${link('yelp2023','Yelp’s 2023 Trust &amp; Safety report')} separately describes recommended, not recommended, moderator-removed and author-removed reviews. Its contribution breakdown and US report outcomes also have different geographic bases.</p>
      <h3>Can a removal service make a review recommended?</h3><p>Yelp says no person can override an individual software recommendation. If your concern is a possible content-policy breach, that is a separate reporting question. ReviewRemoval assesses specific policy concerns; a quote does not purchase a recommendation change. ${link('yelpHelp','Yelp’s explanation')} · <a href="../remove-yelp-reviews.html">Our Yelp service</a></p>
      <h3>What if the review actually violates a rule?</h3><p>Preserve the post and identify the exact concern before reporting. ${link('yelpReport','Yelp’s reporting instructions')} describe the available route and decision notification. Our <a href="review-report-evidence-checklist.html">evidence checklist</a> helps separate an observable fact from a suspicion. A genuine critical review may remain.</p>
      <h2 id="method">Methods, limitations and reuse</h2>
      <p>We transcribed the four transition counts and cohort summary into <code>research-data.cjs</code>. Our build script calculates row totals, conditional shares, endpoint movement and net change, then produces the CSV and chart from those values. Reproduce the results by adding the four cells and using the formulas above. We did not collect new Yelp reviews or replicate the authors’ crawls.</p>
      <ul><li><strong>Historical evidence:</strong> classifications and platform systems can change after the study.</li><li><strong>Matched-survivor sample:</strong> the transition matrix excludes reviews absent from either endpoint. It cannot estimate deletion rates or the experience of all original reviews.</li><li><strong>No causal finding:</strong> the matrix does not establish why any review moved.</li><li><strong>No Canadian rate:</strong> applying these percentages to Toronto, Montréal or other Canadian cities would be unsupported.</li><li><strong>No guaranteed outcome:</strong> tracking improves the record; it does not alter eligibility for removal.</li></ul>
      <div class="note-box"><h3>Suggested citation</h3><p>ReviewRemoval (2026). <em>Why Yelp reviews disappear and reappear: a data audit.</em> September 27, 2026. Original calculations from Amos et al., <em>Reviews in Motion</em>, Tables I–II. You may reuse our chart and calculations with a link to this article and attribution to the underlying researchers.</p></div>
      <h2 id="sources">Primary sources</h2><ol class="sources-list"><li>${link('yelpPaper','Amos, Maio, Mittal and Calandrino, Reviews in Motion (2022)')} — Tables I–II. The paper includes a disclaimer that it does not necessarily reflect the FTC’s views.</li><li>${link('yelpProject','Research project and data access information')}.</li><li>${link('yelpHelp','Yelp: How We Approach Reviews')} — current recommendation explanation.</li><li>${link('yelp2023','Yelp Trust &amp; Safety Report 2023')} — distinct recommendation and moderation categories.</li><li>${link('yelpReport','Yelp: How do I report a review?')}</li></ol><p class="research-small">Sources checked September 27, 2026.</p>
    `
  },
  {
    slug:'tripadvisor-fake-review-statistics-removal-rates',type:'Research / Tripadvisor',art:'4 reports',minutes:9,
    published:'2026-09-27',dateLabel:'September 27, 2026',
    title:'Tripadvisor fake review statistics: what removal numbers mean',
    description:'An audit of Tripadvisor fraud data for 2018, 2020, 2022 and 2024. Charts, CSVs and the difference between blocked reviews, reports and removal rates.',
    deck:'Four reporting periods, three different denominators. We trace the fraud figures and explain why a platform-wide total cannot tell you whether a business report will succeed.',
    serviceHref:'../remove-tripadvisor-reviews.html#quote',serviceLabel:'Discuss a Tripadvisor review',
    toc:[['findings','The findings'],['series','Four reporting periods'],['differences','Conflicting source figures'],['blocked','Blocked versus removed'],['reports','The 43% question'],['screening','The 2024 screening split'],['overlap','Overlapping categories'],['canada','Canadian business context'],['questions','Questions answered'],['method','Methods and reuse'],['sources','Primary sources']],
    body:`
      <p class="lede">“Fake reviews removed” and “business reports accepted” measure different things. Tripadvisor’s disclosures offer unusually useful numbers, but combining them without preserving their denominators produces an answer the data cannot support.</p>
      <h2 id="findings">What this audit adds</h2>
      <p>We align four public reporting periods by the year the activity occurred, keep source percentages separate from calculated ratios, and reconstruct two moderation examples. This is an analysis of published company data, not an independent fraud survey or a success-rate study of ReviewRemoval clients.</p>
      <div class="stat-strip"><div><strong>4 periods</strong><span>2018, 2020, 2022 and 2024 activity, with source links</span></div><div><strong>≈8.7%</strong><span>2024 ratio from rounded fraud and review counts</span></div><div><strong>43%</strong><span>Reported community-removal share for 2020 only</span></div></div>
      <p>The important questions are specific: How many reviews were submitted? Which were identified as fraudulent? Were they stopped before publication? And what happened to the smaller group someone reported? Each answer needs a different denominator.</p>
      <h2 id="series">Tripadvisor fake review data, 2018–2024</h2>
      ${table('Selected published periods: activity year is different from report year',['Activity / report year','Review submissions','Detected fraud share','Before publication¹'],D.tripadvisor.map(r=>[`${r.year} / ${r.report}`,`${r.qualifier==='rounded'?'≈':'>'}${r.reviews}m`,`${r.year===2024?'≈8.7%²':r.fakePercent+'%'}`,r.blockedPercent===null?'Not stated³':r.blockedPercent+'%']))}
      <p class="research-small">¹ Share of identified fraudulent submissions, not all reviews. ² Our ratio, 2.7m ÷ 31.1m × 100, uses rounded counts. ³ Not stated in the selected 2025 press release; this is not a zero. Sources: ${link('ta2018','2019 report')}, ${link('ta2020','2021 release')}, ${link('ta2022','2023 release')}, ${link('ta2024','2025 release')}.</p>
      <figure><img src="assets/tripadvisor-fraud-series.svg" width="1200" height="672" loading="lazy" alt="Detected fraud shares in the selected contemporary sources were 2.1% for 2018, 3.6% for 2020 and 4.4% for 2022; our approximate ratio for 2024 is 8.7%, calculated from rounded counts. A later source gives a different 2018 figure, discussed below."><figcaption>Figure 1. The outline bar is a calculated ratio. The 2018 bar preserves the original 2019 report’s figure; see the <a href="#differences">later source discrepancy</a> below. These are selected reporting years, not a complete annual series. <a href="assets/tripadvisor-fraud-series.svg" download>Download the SVG chart</a>.</figcaption></figure>
      <p>A higher detected share does not establish that travellers encountered more fraud. Detection capability, submission patterns, policy scope and reporting definitions can affect it. These publications do not hold those factors constant. Connecting the bars would imply observations for intervening years, so our chart uses separate bars.</p>
      <p>The 2024 calculation is approximately 8.6817%, rounded to one decimal. It is tempting to present more digits as greater accuracy. That would be misleading: the two source counts were already rounded. We publish the inputs and formula so a researcher can reproduce the ratio without mistaking it for an exact population estimate.</p>
      <div class="download-row"><a class="download-link" href="data/tripadvisor-review-fraud-2018-2024.csv" download>Download the four-period data (CSV)</a><a class="download-link" href="data/tripadvisor-screening-2024.csv" download>Download screening percentages (CSV)</a></div>
      <h2 id="differences">Why do sources give 2.1% or 2.4% for 2018?</h2>
      <p>The original ${link('ta2018','2019 report')} states 2.1% for 2018. The ${link('ta2023Full','2023 full report’s retrospective')} gives 2.4% for that same activity year. The difference is <strong>0.30 percentage points</strong>. The cited passages do not establish why the figures differ. We do not label this a correction, a policy change or a measurement error without further evidence.</p>
      <p>For 2022, there is a simpler precision difference: the ${link('ta2022','press release')} gives 4.4%, while the ${link('ta2023Full','full report')} gives 4.37%. Rounding 4.37% to one decimal gives 4.4%. That explanation fits the 2022 pair; it does not resolve the 2018 disagreement.</p>
      <p>Our chart is an audit of the selected contemporary publications, not a reconciled historical series. Anyone studying a trend should preserve the publication version beside each value. Mixing the original 2018 baseline with a later retrospective without disclosing the choice can change a calculated comparison.</p>
      <p><a class="download-link" href="data/tripadvisor-source-differences.csv" download>Download the source differences (CSV)</a></p>
      <h2 id="blocked">A prevented submission is not a visible review taken down</h2>
      <p>The 2019 report says 73% of detected fraudulent 2018 submissions were prevented before posting. It separately records <strong>374,220 fraudulent reviews removed after publication</strong>. The report also gives a broader 4.7% rejection-or-removal share, covering guideline violations as well as fraud. Those are distinct measures. ${link('ta2018','2019 report, pages 6 and 17')}</p>
      <p>Here is our normalization of the later pre-publication percentages to <strong>1,000 hypothetical detected fraudulent submissions</strong>. It changes the scale, not the reported relationship.</p>
      ${table('Illustration per 1,000 detected fraudulent submissions; these are not actual counts',['Period','Before posting','Remaining share'],[[2018,730,270],[2020,671,329],[2022,720,280]])}
      <p>The remaining column is simply 1,000 minus the before-posting amount. It does not measure how long content was visible, how often it was read, or how many cases involved an owner’s report. The 2023 release says 72% of 2022 identified fake reviews were stopped before posting; the 2021 release gives 67.1% for 2020. ${link('ta2022','2023 release')} · ${link('ta2020','2021 release')}</p>
      <h2 id="reports">Does Tripadvisor remove 43% of reported reviews?</h2>
      <p>For <strong>2020</strong>, Tripadvisor reported that travellers or businesses flagged 1.0% of reviews and that 43% of community-reported reviews were removed after assessment. Its separate platform-wide rejected-or-removed share was 8.6%. The three percentages describe different groups. ${link('ta2020','2021 disclosure')}</p>
      <p>Normalize those rounded percentages to an illustrative 10,000 submissions: roughly 100 would be community-reported, and roughly 43 of those reports would result in removal. Multiplying 1.0% × 43% gives <strong>0.43% of all submissions</strong> in this illustration. It does not mean only 0.43% of problematic content was handled; other moderation routes were also operating.</p>
      <p>The denominator for 43% is the <em>reported set</em>. People do not report a random sample: they select content they think needs attention. A platform may also act on a review before someone reports it. This selection makes a community-report proportion unsuitable as the odds for a randomly chosen review, a Canadian hotel, or a new client.</p>
      <div class="note-box"><h3>How to cite the 43% figure accurately</h3><p>State the activity year, the reporting group and the outcome. The figure concerns community reports assessed in 2020. It is not a current removal promise, and the selected 2025 release does not supply an updated equivalent.</p></div>
      <h2 id="screening">The 2024 screening numbers are not all additive</h2>
      <p>The 2025 release describes three initial automated outcomes: 87.8% meeting standards, 7.3% rejected by technology and 4.9% sent for further review. It separately says the human team moderated 4.2 million reviews, or 13.5%, before or after posting. ${link('ta2024','2025 disclosure')}</p>
      <figure><img src="assets/tripadvisor-screening-2024.svg" width="1200" height="672" loading="lazy" alt="Initial automated outcomes total 100%: 87.8% met standards, 7.3% rejected, 4.9% flagged for further review. The separate 13.5% human-moderated figure covers before and after posting and should not be added."><figcaption>Figure 2. Our diagram separates the initial split from the broader human-work measure. ${link('ta2024','Source: 2025 release')}. <a href="assets/tripadvisor-screening-2024.svg" download>Download the SVG</a>.</figcaption></figure>
      <p>The initial percentages sum to 100%. Adding 13.5% creates a fictitious 113.5% pie. Subtracting 4.9% from 13.5% to claim that precisely 8.6% were investigated only after posting is also unsupported: these are process measures with rounding and potentially different inclusion rules, not a published disjoint partition.</p>
      <h2 id="overlap">Why AI and employee-incentive counts need care</h2>
      <p>Tripadvisor also reported 214,000 AI-generated reviews flagged and removed, 360,000 removed reviews linked to employee incentive programmes, and a 54% review-boosting share of detected fraud in 2024. ${link('ta2024','2025 disclosure')}</p>
      <p>Those descriptions concern different dimensions: how text was produced, the incentive attached to posting, and the purpose of manipulation. A single post could fit more than one description. The selected release does not supply an intersection table. We therefore do not add them to the 2.7 million fraud total or turn them into mutually exclusive chart slices.</p>
      <p>The same caution applies when comparing platforms. Google’s broad policy-violating review totals and Trustpilot’s detected fake-review counts do not share a definition or denominator with this series. Use our <a href="google-review-moderation-2019-2025.html">Google audit</a> and <a href="trustpilot-fake-reviews-by-star-rating.html">Trustpilot analysis</a> for the source definitions rather than combining them into a league table.</p>
      <h2 id="canada">What Canadian hotels and restaurants can use</h2>
      <p>These global figures do not estimate fraud in Toronto, Niagara, Montréal, Banff, Vancouver or any other destination. A Canadian business can use the definitions to organize its own records, but it cannot multiply its review count by 8.7% and conclude that the result is fake.</p>
      <p>A practical case record should contain the property URL, exact review URL, date observed, the suspected policy issue, and any relevant first-hand evidence. Distinguish a post on Tripadvisor from a similarly worded Google or Booking.com review. For several properties, keep separate rows rather than treating the brand as one listing.</p>
      <p>${link('canada','ISED’s Canadian tourism SME report')} provides national business context, not Tripadvisor removal outcomes. Our <a href="canadian-tourism-google-reviews-2023.html">Canadian data article</a> and <a href="../review-removal-canada.html">Canada service page</a> keep that distinction explicit. The ${link('bureau','Competition Bureau’s review guidance')} also cautions against suppressing genuine, relevant and lawful reviews.</p>
      <h2 id="questions">Questions the figures cannot answer alone</h2>
      <h3>How likely is my Tripadvisor review to be removed?</h3><p>No client-level probability follows from these aggregate reports. Eligibility depends on the specific review, platform rule and evidence. An assessment should address those facts rather than turn a historical global statistic into a sales promise.</p>
      <h3>How long will removal take?</h3><p>A historical assessment-speed statistic is not a current completion deadline. Assessment and removal are also different events. Keep your actual case notices and use the platform’s current guidance for the next step.</p>
      <h3>Is a one-star review automatically suspicious?</h3><p>No. A low score can describe a genuine experience. If you identify a specific rule concern, ${link('taConcern','Tripadvisor’s business guidance')} describes submitting it through the management tools. Our <a href="review-report-evidence-checklist.html">evidence guide</a> explains how to keep a report focused.</p>
      <h2 id="method">Methods and reuse</h2>
      <ol><li>We selected the 2019 report and 2021, 2023 and 2025 company releases. We indexed each row by its activity year, not its publication year. We cross-checked the 2023 full report and documented its differing historical value separately.</li><li>We retained published percentages for 2018–2022. For 2024 only, we divided the rounded 2.7 million fraud count by the rounded 31.1 million review count. The CSV marks that different basis.</li><li>We normalized before-posting percentages to 1,000 and the 2020 reporting example to 10,000 for illustration. These are scale examples, not observed counts.</li><li>We kept unavailable fields blank, did not fill intervening years and did not infer non-overlapping categories.</li><li>We did not obtain review-level data, audit detection accuracy, estimate undetected fraud or measure Canadian removal outcomes.</li></ol>
      <div class="note-box"><h3>Suggested citation</h3><p>ReviewRemoval (2026). <em>Tripadvisor fake review statistics: what removal numbers mean.</em> September 27, 2026. Analysis of Tripadvisor disclosures covering 2018, 2020, 2022 and 2024. Reuse our charts or calculations with a link to this page and cite the underlying company publications.</p></div>
      <h2 id="sources">Primary sources</h2><ol class="sources-list"><li>${link('ta2018','Tripadvisor Review Transparency Report 2019')} — 2018 activity; rejection, fraud and pre-publication figures.</li><li>${link('ta2020','Tripadvisor’s October 27, 2021 disclosure')} — 2020 submissions and community-report outcomes.</li><li>${link('ta2022','Tripadvisor’s April 11, 2023 disclosure')} — 2022 submissions and fraud figures.</li><li>${link('ta2024','Tripadvisor’s March 18, 2025 disclosure')} — 2024 screening, fraud and related categories. ${link('taReport','Full report landing page')}.</li><li>${link('taConcern','Tripadvisor for Business: reporting concerns')}.</li><li>${link('canada','ISED, SME Profile 2023: Tourism industries in Canada')}.</li><li>${link('bureau','Competition Bureau, Deceptive Marketing Practices Digest, Volume 3')}.</li></ol><p class="research-small">Sources checked September 27, 2026. Company data are self-reported. This article does not present 2024 figures as measurements of 2026 activity.</p>
    `
  }
];
